In [1]:
%load_ext autoreload
%autoreload 2

In [7]:
from pose_regressors import DensePoseRegressorV5
import torch

In [5]:
x = torch.rand(2, 128, 60, 80)

In [9]:
model = DensePoseRegressorV5(128)

In [10]:
model(x)

torch.Size([2, 128, 1, 1])


(tensor([[ 0.8140, -0.3003,  0.4167,  0.2713],
         [ 0.6954, -0.5422,  0.4403,  0.1689]], grad_fn=<DivBackward0>),
 tensor([[-0.5430,  0.2178,  0.0960],
         [-0.6022,  0.2278,  0.0722]], grad_fn=<SqueezeBackward1>))

In [1]:
%load_ext autoreload
%autoreload 2

In [9]:
import sys
sys.path.append('../../src')

In [37]:
!pip install timm=="0.3.2"

     |████████████████████████████████| 244 kB 1.3 MB/s eta 0:00:01


In [28]:
from depo import depo_v8
from utils.model import count_parameters

In [23]:
%%timeit -r 10 -n 10

img_q = torch.rand(1, 3, 480, 640).cuda()
img_s = torch.rand(1, 3, 480, 640).cuda()
K_q = torch.rand(1, 3, 3).cuda()
K_s = torch.rand(1, 3, 3).cuda()
scales_q = torch.ones(1, 2).cuda()
scales_s = torch.ones(1, 2).cuda()

13.2 ms ± 2.19 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)


In [29]:
model = depo_v8().cuda()

In [30]:
count_parameters(model) / 10 ** 6

21.098492

In [31]:
%%timeit -r 10 -n 10

img_q = torch.rand(1, 3, 480, 640).cuda()
img_s = torch.rand(1, 3, 480, 640).cuda()
K_q = torch.rand(1, 3, 3).cuda()
K_s = torch.rand(1, 3, 3).cuda()
scales_q = torch.ones(1, 2).cuda()
scales_s = torch.ones(1, 2).cuda()

with torch.no_grad():
    out = model(img_q, img_s, K_q, K_s, scales_q, scales_s)

64 ms ± 4.74 ms per loop (mean ± std. dev. of 10 runs, 10 loops each)


In [25]:
img_q = torch.rand(1, 3, 480, 640).cuda()
img_s = torch.rand(1, 3, 480, 640).cuda()
K_q = torch.rand(1, 3, 3).cuda()
K_s = torch.rand(1, 3, 3).cuda()
scales_q = torch.ones(1, 2).cuda()
scales_s = torch.ones(1, 2).cuda()

with torch.no_grad():
    out = model(img_q, img_s, K_q, K_s, scales_q, scales_s)

In [27]:
out[0]

tensor([[[[-0.1781, -0.1955, -0.1908,  ..., -0.2095, -0.2007, -0.2096],
          [-0.1724, -0.1880, -0.1848,  ..., -0.2033, -0.2097, -0.2121],
          [-0.1819, -0.1706, -0.1859,  ..., -0.2091, -0.2012, -0.2161],
          ...,
          [-0.1951, -0.2040, -0.2005,  ..., -0.1991, -0.2286, -0.2184],
          [-0.2006, -0.2015, -0.1926,  ..., -0.2073, -0.2106, -0.2208],
          [-0.1953, -0.1916, -0.1830,  ..., -0.2082, -0.2215, -0.1926]],

         [[-0.1419, -0.1575, -0.1502,  ..., -0.1770, -0.1692, -0.1785],
          [-0.1362, -0.1483, -0.1453,  ..., -0.1742, -0.1798, -0.1819],
          [-0.1420, -0.1358, -0.1480,  ..., -0.1784, -0.1728, -0.1850],
          ...,
          [-0.1304, -0.1395, -0.1390,  ..., -0.1519, -0.1830, -0.1718],
          [-0.1377, -0.1401, -0.1388,  ..., -0.1650, -0.1687, -0.1758],
          [-0.1334, -0.1315, -0.1243,  ..., -0.1675, -0.1780, -0.1530]]]],
       device='cuda:0')

In [1]:
import torch

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [23]:
H = 60
W = 80
B = 3
C = 128

x = torch.rand(B, C, H, W)
y = x

In [24]:
x = x.contiguous().view((B, C, H*W)).transpose(2, 1)
print(x.size())
x = x.transpose(2, 1).contiguous().view(B, -1, H, W)
print(x.size())

torch.Size([3, 4800, 128])
torch.Size([3, 128, 60, 80])


In [25]:
y = y.flatten(2).transpose(2, 1)
print(y.size())
y = y.transpose(2, 1).unflatten(2, (H, W))
print(y.size())

torch.Size([3, 4800, 128])
torch.Size([3, 128, 60, 80])


In [26]:
(x == y).all()

tensor(True)

In [1]:
import torch

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
x = torch.rand(3, 2)
x

tensor([[0.9109, 0.6929],
        [0.5717, 0.5017],
        [0.4097, 0.6406]])

In [3]:
x.flatten()

tensor([0.9109, 0.6929, 0.5717, 0.5017, 0.4097, 0.6406])